[package]
name          = "cw721-base"
description   = "`cw721-base` with generic `TNftExtension` and `TCollectionExtension` for empty, on-chain metadata, or custom extensions"
authors       = [
  "mr-t <mr-t@arkprotocol.io>",
  "Ethan Frey <ethanfrey@users.noreply.github.com>",
  "Orkun Külçe <orkun@deuslabs.fi>",
]
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
rust-version  = { workspace = true }

[lib]
doctest      = false # disable doc tests
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.5.11", features = ["staking"] }
cosmwasm-schema = "1.5.11"
cw-storage-plus = "1.2.0"
thiserror = "1.0.69"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8.22"

